### PR TITLE
Migrate project to Swift4

### PR DESCRIPTION
**Pull request by korporaal**
Updates to:
* project for Swift4
* TravisCI for XCode9, SDK and simulators
* and add documentation

### CODE REVIEW

**Comment by korporaal** [comment]
Possible enhancements:

ArrayDataSource and SectionDataSource initialisers call the base class init and do not have class specific responsibilities.  Is there any reason to keep them?

The Section could be more useful if there are optional headerView and footerView property.  SectionDataSource could then use the UICollectionView and UITableView data source methods viewForHeader/Footer inSection and display views for each.  If the headerTitle and footerTitle are set, the data source methods could create a simple view with the title.

**Review by fonkadelic — COMMENTED** [review]
@mathiasnagler Do you know if there is a reason why the initializers are redeclared for `ArrayDataSource` and `SectionedDataSource`?

**Review by fonkadelic — CHANGES_REQUESTED** [review]
The build configuration for this project is defined in `.xcconfig` files (https://github.com/kupferwerk/KWDataSourceKit/blob/master/Configuration/KWDataSourceKit.xcconfig). The Swift version (and other build settings) should be updated there.

**Comment by korporaal** [comment]
@fonkadelic pushed config version changes.

**Review by fonkadelic — APPROVED** [review]

**Comment by fonkadelic** [comment]
@korporaal 👌

**Pull request merged**
